#!/usr/bin/env bash
# =============================================================================
# CodeJudge — deploy / redeploy on the server
# =============================================================================
# Idempotent: safe to re-run for every deploy. Builds both images, rebuilds
# the frontend, and restarts the API.
#
#   ./deploy.sh
#
# Expects, on the box:
#   · docker + docker compose
#   · node/npm (to build the frontend)
#   · a populated .env in the repo root (see .env.example)
# =============================================================================

set -euo pipefail

cd "$(dirname "$0")"

echo "==> Checking prerequisites"

if [ ! -f .env ]; then
    echo "ERROR: no .env in $(pwd)." >&2
    echo "Copy .env.example to .env and fill it in first." >&2
    exit 1
fi

# JWT_SECRET and MONGO_URI are required by compose (${VAR:?}), but failing
# here with a readable message beats failing inside compose's substitution.
for required in MONGO_URI JWT_SECRET CORS_ORIGIN; do
    if ! grep -qE "^${required}=.+" .env; then
        echo "ERROR: ${required} is missing or empty in .env" >&2
        exit 1
    fi
done

# Load .env so BACKEND_IMAGE / ECR_REGISTRY are visible to this script, not
# just to compose. `set -a` exports everything it defines.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

if [ -n "${ECR_REGISTRY:-}" ]; then
    # ── ECR path (production) ────────────────────────────────────────────
    # GitHub Actions already built these on x86 runners. Building here would
    # mean a 1GB box doing work that has been done, and — if the images were
    # ever built on an arm64 laptop — producing binaries the instance can't
    # execute at all.
    echo "==> Authenticating to ECR (${ECR_REGISTRY})"
    aws ecr get-login-password --region "${AWS_REGION:-ap-south-1}" \
        | docker login --username AWS --password-stdin "${ECR_REGISTRY}"

    echo "==> Pulling images"
    docker pull "${BACKEND_IMAGE}"
    docker pull "${DOCKER_RUNNER_IMAGE}"
else
    # ── Local path (development) ─────────────────────────────────────────
    echo "==> Building runner image (this is the slow one)"
    docker build --target runner -t codejudge-runner:latest .

    echo "==> Building backend image"
    docker build --target backend -t codejudge-backend:latest .
fi

echo "==> Building frontend"

# Create React App bakes REACT_APP_* into the bundle at BUILD time, reading
# .env.production in preference to .env. The developer's frontend/.env points
# at http://localhost:5001/api — building with that would ship a bundle whose
# API calls go to the *visitor's* machine.
#
# "/api" (relative) is correct for the same-origin Caddy setup: it resolves
# against whatever domain served the page, so the same build works on any
# hostname without rebuilding.
#
# Regenerated every deploy so it can never drift from the root .env.
GOOGLE_CLIENT_ID=$(grep -E '^GOOGLE_CLIENT_ID=' .env | cut -d= -f2- | tr -d '"' || true)

cat > frontend/.env.production <<EOF
# Generated by deploy.sh — do not edit, changes are overwritten.
REACT_APP_API_URL=/api
REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
EOF

(
    cd frontend
    npm ci
    # CI=true turns warnings into errors on some setups; this is a deploy,
    # not a lint gate.
    CI=false npm run build
)

echo "==> Restarting API"
docker compose up -d

echo "==> Waiting for health check"
for i in $(seq 1 30); do
    if curl -fsS http://127.0.0.1:5001/healthz > /dev/null 2>&1; then
        echo "    healthy after ${i}s"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "ERROR: backend did not become healthy in 30s. Logs:" >&2
        docker compose logs --tail 40 backend >&2
        exit 1
    fi
    sleep 1
done

echo "==> Pruning dangling images"
docker image prune -f > /dev/null

echo
echo "Done. Frontend built to frontend/build/ (Caddy serves it from there)."
docker compose ps
